# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe1d9627b60f71e42c34a15d898190f4436477006ce3acba0ee8ab7865d99c4691ed1c9e70f4471ec8e389ca97433b3f77f8aff124f688136a2d7da7c1b3ee92

test:
  secret_key_base: 750b8e097e56a52cbf34a54043647c0959d0eaf78f7ee045b3241e1a2aa03a73d95ee202c3b2ff9f6ecff2efdeecc2995bc68592abc92bbad643d3f84c5a3f30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
